### ISSUE TITLE
当某月1号为周一的时候，周选择器异常

### ISSUE THREAD

**Issue by vip55zxc** [zoux/dayjs-plugin-weekofmonth#1]
您好很荣幸可以接手您的代码，在您的代码里学到了很多知识

https://vs-code-background.oss-cn-beijing.aliyuncs.com/WX20220805-110749.png
https://vs-code-background.oss-cn-beijing.aliyuncs.com/WX20220805-110813.png

**Comment by zoux** [comment]
> 您好很荣幸可以接手您的代码，在您的代码里学到了很多知识
> 
> https://vs-code-background.oss-cn-beijing.aliyuncs.com/WX20220805-110749.png https://vs-code-background.oss-cn-beijing.aliyuncs.com/WX20220805-110813.png

你好。我跑了下8月份的插件运算：
```javascript
import dayjs from 'dayjs' // v1.11.4
import weekOfMonth from '@zouxin/dayjs-plugin-weekofmonth' // v1.0.0

dayjs.extend(weekOfMonth, { offset: 1 })

console.log(dayjs().weekMapOfMonth())
```

结果如下：
```json
{
    "0": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
    ],
    "1": [
        8,
        9,
        10,
        11,
        12,
        13,
        14
    ],
    "2": [
        15,
        16,
        17,
        18,
        19,
        20,
        21
    ],
    "3": [
        22,
        23,
        24,
        25,
        26,
        27,
        28
    ],
    "4": [
        29,
        30,
        31
    ]
}
```

可以看到索引第0项、第1项，是有正确运算8月第一周0801-0807、8月第二周0808-0814的。

因此可初步判定插件输出结果是无误的。

从你的截图来看，我推测是将插件计算结果转化为月&周维度显示时，对周的判定匹配逻辑出了问题。建议你再review并调试下对应业务逻辑哈。

**Comment by vip55zxc** [comment]
谢谢作者的回复哈，定位到 bug 了并已修复，确实是业务逻辑的问题，再次感谢哈，祝你生活工作愉快
